# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmahasim <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/09 17:18:27 by mmahasim          #+#    #+#              #
#    Updated: 2019/04/10 16:27:01 by mmahasim         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ./ft_display_file.c

all = $(NAME)

$(NAME):
	gcc -o ft_display_file -Wall -Wextra -Werror $(SRC)
	gcc -c $(SRC)

clean: 
	rm -f *.o

fclean:	
	rm -f $(NAME)
